---
# install docker
- name: install docker
  when: 
  - "HTTP_SERVER is defined"
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
  script: "{{ lookup('first_found', findme)}}"
  vars:
    findme:
      - install-{{ ansible_distribution }}.sh  
      - install.sh    