- name: Run prepare.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    RKT_ACI_KUBELET: '{{ RKT_ACI_KUBELET }}'
    REGISTRY_LOCAL: '{{ REGISTRY_LOCAL }}'
    REGISTRY_KUBELET_REPO: '{{ K8S_IMAGES["KUBELET"]["NAME"] }}'
    REGISTRY_KUBELET_VERSION: '{{ K8S_IMAGES["KUBELET"]["VERSION"] }}' 
  script: scripts/prepare.sh

- name: copy config/kubelet.yaml
  template: src=config/kubelet.yaml dest=/etc/kubernetes/config/kubelet.yaml

- name: copy scripts/kubelet.sh
  template: src=scripts/kubelet.sh dest=/etc/kubernetes/scripts/kubelet.sh mode=0755

- name: check need services/k8s-kubelet.service
  raw: stat /etc/systemd/system/k8s-kubelet.service
  register: need_services_kubelet
  ignore_errors: True

- name: template services/k8s-kubelet.service
  template: src=services/kubelet.service dest=/etc/systemd/system/k8s-kubelet.service

- name: start services k8s-kubelet.service
  raw: systemctl daemon-reload && systemctl enable k8s-kubelet.service && systemctl start k8s-kubelet.service
  when: need_services_kubelet is failed