- name: Run cache.sh
  environment:
    REGISTRY_LOCAL: '{{ REGISTRY_LOCAL }}'
    REGISTRY_REMOTE: '{{ REGISTRY_REMOTE }}'
    REGISTRY_DATA_PATH: '{{ REGISTRY_DATA_PATH }}'
    ITEM_REPO: '{{ item.value.NAME }}'
    ITEM_VERSION: '{{ item.value.VERSION }}'
  script: cache.sh
  with_dict: '{{ K8S_IMAGES }}'