clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod-devops/git:1.5.0

pipeline:  

  docker:
    image: registry.cn-qingdao.aliyuncs.com/wod-devops/docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/ansible:2.7.10
    repo: wod/ansible-kubernetes
    version: v1.16.0 
    channel: alpha
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD

  harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod-devops/harbor:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    registry: registry.cn-qingdao.aliyuncs.com
    repo: wod/ansible-kubernetes
    tag: v1.16.0
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
      
  harbor-latest:
    image: registry.cn-qingdao.aliyuncs.com/wod-devops/harbor:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    registry: registry.cn-qingdao.aliyuncs.com
    repo: wod/ansible-kubernetes
    tag: latest
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master
