clone:
  git:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/git:1.4.0
pipeline:
  docker-aliyun-alpha:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry-vpc.cn-qingdao.aliyuncs.com/wod/ansible:2.3.0-centos7
    repo: wod-cloud/ansible-kubernetes
    version: v1.13.3
    channel: alpha
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: dev        
  docker-aliyun:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry-vpc.cn-qingdao.aliyuncs.com/wod/ansible:2.3.0-centos7
    repo: wod-cloud/ansible-kubernetes
    version: v1.13.3
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master      
  docker-aliyun-latest:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry-vpc.cn-qingdao.aliyuncs.com/wod/ansible:2.3.0-centos7
    repo: wod-cloud/ansible-kubernetes
    version: latest
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master
branches: [master,dev]
