clone:
  git:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/git:1.5.0

pipeline:  

  docker:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry-vpc.cn-qingdao.aliyuncs.com/wod/ansible:2.7.10
    repo: wod/ansible-kubernetes
    version: v1.15.4 
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master

  harbor:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/harbor:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    repo: wod-cloud/ansible-kubernetes
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master

  docker-latest:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/docker:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry-vpc.cn-qingdao.aliyuncs.com/wod/ansible:2.7.10
    repo: wod/ansible-kubernetes
    version: latest
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master
      
  harbor-latest:
    image: registry-vpc.cn-qingdao.aliyuncs.com/wod-devops/harbor:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    registry: registry-vpc.cn-qingdao.aliyuncs.com
    repo: wod-cloud/ansible-kubernetes
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch: master
