---
apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: {{ REGISTRY_LOCAL }}{{ K8S_IMAGES['KUBE-PROXY']['NAME'] }}:{{ K8S_IMAGES['KUBE-PROXY']['VERSION'] }}
    command:
    - kube-proxy
    - --config=/etc/kubernetes/config/kube-proxy-conf.yaml
    - --ipvs-min-sync-period=5s 
    - --ipvs-sync-period=5s 
    - --ipvs-scheduler=rr    
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/log
      name: varlog
      readOnly: false
    - mountPath: /run/xtables.lock
      name: xtables-lock    
    - mountPath: /etc/ssl/certs
      name: "etc-ssl-certs"
    - mountPath: /etc/kubernetes/ssl
      name: "etc-kube-ssl"
      readOnly: true
    - mountPath: /etc/kubernetes/config
      name: "etc-kubernetes-config"
      readOnly: true      
    - mountPath: /lib/modules
      name: "lib-modules"
  volumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: xtables-lock
    hostPath:
      path: /run/xtables.lock
      type: FileOrCreate  
  - name: "etc-ssl-certs"
    hostPath:
      path: "/usr/share/ca-certificates"
  - name: "etc-kube-ssl"
    hostPath:
      path: "/etc/kubernetes/ssl"
  - name: "etc-kubernetes-config"
    hostPath:
      path: "/etc/kubernetes/config"
  - name: "lib-modules"
    hostPath:
      path: "/lib/modules"