---
- name: Run prepare.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    RKT_ACI_NGINX: '{{ RKT_ACI_NGINX }}'
    REGISTRY_REMOTE: '{{ REGISTRY_REMOTE }}'
    REGISTRY_REMOTE_SPLIT: '{{ REGISTRY_REMOTE_SPLIT }}'
    REGISTRY_REPO_NGINX: '{{ K8S_IMAGES["NGINX"]["NAME"] }}'
    REGISTRY_VERSION_NGINX: '{{ K8S_IMAGES["NGINX"]["VERSION"] }}'    
  script: prepare.sh

- name: check need prepare.sh
  raw: stat /etc/kubernetes/scripts/nginx-prepare.sh
  register: need_scripts_prepare
  ignore_errors: True

- name: copy prepare.sh
  copy: src=prepare.sh dest=/etc/kubernetes/scripts/nginx-prepare.sh mode=0755
  when: need_scripts_prepare | failed  

- name: check need k8s-nginx.service
  raw: stat /etc/systemd/system/k8s-nginx.service
  register: need_services_registry
  ignore_errors: True  
  when: REGISTRY_LOCAL_HOSTNAME == inventory_hostname

- name: template k8s-nginx.service
  template: src=k8s-nginx.service dest=/etc/systemd/system/k8s-nginx.service mode=0644
  when: need_services_registry | failed

- name: start k8s-nginx.service
  raw: systemctl daemon-reload && systemctl enable k8s-nginx.service && systemctl start k8s-nginx.service
  when: need_services_registry | failed
