---
# install sys
- name: sys.sh
  environment:
    REGISTRY_LOCAL_HOST: '{{ REGISTRY_LOCAL_HOST }}'
    REGISTRY_LOCAL_IP: '{{ REGISTRY_LOCAL_IP }}'
    AUTHORIZED_KEYS: '{% for ssh_key in SSH_INSTALL_KEYS %}{{ SSH_KEYS[ssh_key] }}{% if loop.last %}{% else %},{% endif %}{% endfor %}'
  script: sys.sh  

- name: centos.sh
  when: "ansible_distribution == 'CentOS'"
  script: centos.sh