---
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://{{ K8S_MASTER_IP }}:{{ K8S_MASTER_PORT }}
    certificate-authority: /etc/kubernetes/ssl/ca.pem
users:
- name: kubeproxy
  user:
    client-certificate: /etc/kubernetes/ssl/kube-proxy.pem
    client-key: /etc/kubernetes/ssl/kube-proxy.key
contexts:
- context:
    cluster: local
    user: kubeproxy
  name: kubeproxy-context
current-context: kubeproxy-context