kind: Pod
apiVersion: v1
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  labels:
    component: traefik
    tier: control-plane
  name: kube-traefik
  namespace: kube-system
spec:
  hostNetwork: true
  priorityClassName: system-cluster-critical
  serviceAccountName: kube-traefik
  volumes:
  - name: config
    configMap:
      name: kube-traefik-conf
  - name: acme
    hostPath:
        path: /etc/kubernetes/data/traefik/acme.json
  - name: etc-localtime
    hostPath:
      path: /etc/localtime  
  containers:
  - name: kube-traefik
    image: {{ REGISTRY_LOCAL }}{{ CLOUD_IMAGES['TRAEFIK']['NAME'] }}:{{ CLOUD_IMAGES['TRAEFIK']['VERSION'] }}
    volumeMounts:
    - name: config
      mountPath: /config
    - name: acme
      mountPath: /acme.json
    - name: etc-localtime
      mountPath: /etc/localtime
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 80
      hostPort: 80
      name: http
    - containerPort: 8380
      hostPort: 8380
      name: admin
    args:
    - --configfile=/config/traefik.toml
    - --kubernetes