---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-traefik
subjects:
- kind: ServiceAccount
  name: kube-traefik
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-traefik
  namespace: kube-system
---  
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-traefik-conf
  namespace: kube-system
data:
  traefik.toml: |
    defaultEntryPoints = ["http","https"]
    [entryPoints.traefik]
      address = ":8380"
    [websocket]
      protocol = "http"
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
    [metrics]
      [metrics.prometheus]
        entryPoint = "traefik"
        buckets = [0.1,0.3,1.2,5.0]
    [accessLog]
      format   = "json"
    [api]
      entryPoint = "traefik"
      dashboard = true
    [acme]
      email = "mengkzhaoyun@gmail.com"
      storage = "acme.json"
      onHostRule = true
      entryPoint = "https"
      # caServer = "https://acme-staging.api.letsencrypt.org/directory"    
      acmeLogging = true  
      [acme.tlsChallenge]
        entryPoint = "https"   