- name: mkdir -p /etc/docker
  raw: mkdir -p /etc/docker

- name: check need /etc/docker/daemon.json
  raw: stat /etc/docker/daemon.json
  register: need_docker_daemon
  ignore_errors: True

- name: template /etc/docker/daemon.json
  template: src=daemon.json dest=/etc/docker/daemon.json mode=0644
  when: need_docker_daemon | failed

- name: start docker.service
  raw: systemctl daemon-reload && systemctl enable docker && systemctl restart docker
  when: need_docker_daemon | failed