---
- name: mkdir -p /etc/kubernetes/data/nginx
  raw: mkdir -p /etc/kubernetes/data/nginx

- name: template nginx.conf
  template: src=nginx.conf dest=/etc/kubernetes/data/nginx/nginx.conf mode=0644

- name: check need manifests/kube-nginx.yaml
  raw: stat /etc/kubernetes/manifests/kube-nginx.yaml
  register: need_manifests_nginx
  ignore_errors: True

- name: template manifests/kube-nginx.yaml
  template: src=kube-nginx.yaml dest=/etc/kubernetes/manifests/kube-nginx.yaml
  when: need_manifests_nginx is failed