---
- name: Run prepare.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    RKT_ACI_NGINX: '{{ RKT_ACI_NGINX }}'
    REGISTRY_REMOTE: '{{ REGISTRY_REMOTE }}'
    REGISTRY_REMOTE_SPLIT: '{{ REGISTRY_REMOTE_SPLIT }}'
    REGISTRY_REPO_NGINX: '{{ K8S_IMAGES["NGINX"]["NAME"] }}'
    REGISTRY_VERSION_NGINX: '{{ K8S_IMAGES["NGINX"]["VERSION"] }}'
  script: prepare.sh

- name: check need prepare.sh
  raw: stat /etc/kubernetes/scripts/nginx-prepare.sh
  register: need_scripts_prepare
  ignore_errors: True

- name: copy prepare.sh
  copy: src=prepare.sh dest=/etc/kubernetes/scripts/nginx-prepare.sh mode=0755
  when: need_scripts_prepare | failed  

- name: check need nginx.conf
  raw: stat /etc/kubernetes/data/nginx/nginx.conf
  register: need_nginx_conf
  ignore_errors: True  

- name: template nginx.conf
  template: src=nginx.conf dest=/etc/kubernetes/data/nginx/nginx.conf mode=0644
  when: need_nginx_conf | failed

- name: check need nginx.service
  raw: stat /etc/systemd/system/k8s-nginx.service
  register: need_services_nginx
  ignore_errors: True  

- name: template nginx.service
  template: src=nginx.service dest=/etc/systemd/system/k8s-nginx.service mode=0644
  when: need_services_nginx | failed

- name: start nginx.service
  raw: systemctl daemon-reload && systemctl enable k8s-nginx.service && systemctl start k8s-nginx.service
  when: need_services_nginx | failed