---
- name: copy nginx.sh
  template: src=nginx.sh dest=/etc/kubernetes/scipts/nginx.sh mode=0744

- name: template nginx.conf
  template: src=nginx.conf dest=/etc/kubernetes/data/nginx/nginx.conf mode=0644

- name: check need nginx.service
  raw: stat /etc/systemd/system/k8s-nginx.service
  register: need_services_nginx
  ignore_errors: True  

- name: template nginx.service
  template: src=nginx.service dest=/etc/systemd/system/k8s-nginx.service mode=0644
  when: need_services_nginx | failed

- name: start nginx.service
  raw: systemctl daemon-reload && systemctl enable k8s-nginx.service && systemctl start k8s-nginx.service
  when: need_services_nginx | failed