kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
staticPodPath: /etc/kubernetes/manifests
hairpinMode: promiscuous-bridge
failSwapOn: false
authentication:
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.pem
  anonymous:
    enabled: false
  webhook:
    enabled: true
clusterDomain: cluster.local
clusterDNS:
  - 10.3.0.10
featureGates:
  BlockVolume: true
  ExpandPersistentVolumes: true