---
# iface
IFACE: "{{ ansible_facts['default_ipv4']['interface'] }}"

# host define
HOST_IP: "{{ ansible_facts[IFACE]['ipv4']['address'] }}"

# /root/.ssh
SSH_KEYS: 
  ansible: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCJNFRbNc0SsHa/+mWB71z7SLPH9rQpwEqGbRo7q466a97h3bejNav9wc9AKmepHPfRw7DJfSmWO3lGBya0QkXMYXVvtfcWPvZZDlar5JK/ZsC8HGOpwVLdd1uUfyPu2qM0sjRNA/Ty8PDMkS5dSyZAJNlxUAILRpepkYoT8jhrw== ansible@docker"

# system options
SSH_INSTALL_KEYS: 
  - ansible

# docker
DOCKER_DATA_PATH: /var/lib/docker

# rkt
RKT_DATA_PATH: /var/lib/rkt

# registry
REGISTRY_LOCAL_HOST: reg.local
REGISTRY_LOCAL: "{{ REGISTRY_LOCAL_HOST }}:5000/k8s/"

# REGISTRY_REMOTE_HOST: "172.16.11.23:5000"
REGISTRY_REMOTE: "registry.cn-qingdao.aliyuncs.com/wod/"
REGISTRY_DATA_PATH: /etc/kubernetes/data/registry

# singer master
K8S_TRAEFIK_REPLICAS: "1"
K8S_ADMIN_TOKEN: "pleasechangeit"
K8S_IMAGES: 
  KUBELET:
    NAME: hyperkube
    VERSION: "v1.18.2"
  KUBE-APISERVER:
    NAME: kube-apiserver
    VERSION: "v1.18.2"
  KUBE-CONTROLLER-MANAGER:
    NAME: kube-controller-manager
    VERSION: "v1.18.2"
  KUBE-SCHEDULER:
    NAME: kube-scheduler
    VERSION: "v1.18.2"
  KUBE-PROXY:
    NAME: kube-proxy
    VERSION: "v1.18.2"
  KUBECTL:
    NAME: kubectl
    VERSION: "v1.18.2"
  DASHBOARD:
    NAME: kubernetesui-dashboard
    VERSION: "v2.0.0"
  METRICS-SCRAPER:
    NAME: kubernetesui-metrics-scraper
    VERSION: "v1.0.4"
  METRICSSERVER:
    NAME: metrics-server-amd64
    VERSION: "v0.3.6"
  PAUSE: 
    NAME: pause-amd64
    VERSION: "3.2"
  REGISTRY:
    NAME: registry
    VERSION: "2.7.1"
  ETCD:
    NAME: etcd
    VERSION: "v3.4.4"
  FLANNEL:
    NAME: flannel
    VERSION: "v0.12.0"
  KUBE-ROUTER:
    NAME: kube-router
    VERSION: "v1.0.0-rc1"
  BUSYBOX:
    NAME: busybox
    VERSION: "1.31"
  NGINX:
    NAME: nginx
    VERSION: "1.17.4-alpine"
  COREDNS:
    NAME: coredns
    VERSION: "1.5.2"
  ETCDCTL:
    NAME: etcdctl
    VERSION: "v3.4.4"
  KEEPALIVED:
    NAME: keepalived
    VERSION: "1.4.5"
  HELM:
    NAME: helm
    VERSION: "v2.16.3"
  TILLER:
    NAME: tiller
    VERSION: "v2.16.3"
  TRAEFIK:
    NAME: traefik
    VERSION: "v1.7.18-alpine"
  CALICO-CNI:
    NAME: calico-cni
    VERSION: "v3.13.3"
  CALICO-FLEXVOL:
    NAME: calico-pod2daemon-flexvol
    VERSION: "v3.13.3"
  CALICO-NODE:
    NAME: calico-node
    VERSION: "v3.13.3"        
  CALICO-CONTROLLERS:
    NAME: calico-kube-controllers
    VERSION: "v3.13.3"
  CILIUM:
    NAME: cilium
    VERSION: "v1.7.2"
  CILIUM-OPERATOR:
    NAME: cilium-operator
    VERSION: "v1.7.2"
  CILIUM-HUBBLE:
    NAME: cilium-hubble
    VERSION: "v0.5.0"
  CILIUM-HUBBLE-UI:
    NAME: cilium-hubble-ui
    VERSION: "latest"

# rkt images
RKT_ACI_REGISTRY: "registry-{{ K8S_IMAGES['REGISTRY']['VERSION'] }}.aci"
RKT_ACI_ETCD: "etcd-{{ K8S_IMAGES['ETCD']['VERSION'] }}.aci"
RKT_ACI_KUBELET: "{{ K8S_IMAGES['KUBELET']['NAME'] }}-{{ K8S_IMAGES['KUBELET']['VERSION'] }}.aci"

# ctl tools
RKT_ACI_REGISTRY_DATA: "registry-data-{{ K8S_IMAGES['KUBELET']['VERSION'] }}"

# k8s adv option.
K8S_NETWORK_PLUGIN: kube-router
K8S_CNI_BIN: cni-plugins-linux-amd64-v0.8.5
K8S_POD_NETWORK: 10.2.0.0/16
K8S_SERVICE_IP_RANGE: 10.3.0.0/16
K8S_SERVICE_PORT_RANGE: 10000-32767
K8S_SERVICE_IP: 10.3.0.1
K8S_DNS_SERVICE_IP: 10.3.0.10
K8S_ADVERTISE_IP: "{{ HOST_IP }}"
K8S_PORT: 6443
K8S_MASTER_DOMAIN: k8s.{{ K8S_DOMAIN }}
K8S_MASTER_PORT: "{{ K8S_PORT }}"

# ubuntu
DEB_RKT: rkt_1.30.0-1_amd64.deb

# centos
YUM_RKT: rkt-1.30.0-1.x86_64.rpm

# other
HTTP_SERVER: https://dl.wodcloud.com/k8s

CLOUD_IMAGES: 

K8S_DOMAIN: "wodcloud.local"

K8S_DOMAIN_ADDONS:
  DASHBOARD: "k8s.{{ K8S_DOMAIN }}"
  METRICS-SCRAPER: "scraper.{{ K8S_DOMAIN }}"
  TRAEFIK: "traefik.{{ K8S_DOMAIN }}"
  HUB: "hub.{{ K8S_DOMAIN }}"
  HUBBLE: "hubble.{{ K8S_DOMAIN }}"