---
# host define
HOST_IP: "{{ ansible_default_ipv4['address'] }}"

# /root/.ssh
SSH_KEYS: 
  ansible: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCJNFRbNc0SsHa/+mWB71z7SLPH9rQpwEqGbRo7q466a97h3bejNav9wc9AKmepHPfRw7DJfSmWO3lGBya0QkXMYXVvtfcWPvZZDlar5JK/ZsC8HGOpwVLdd1uUfyPu2qM0sjRNA/Ty8PDMkS5dSyZAJNlxUAILRpepkYoT8jhrw== ansible@space.docker"
  admin: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCrQGlgFB4TGjJCNk3mJEjgId2Td054T642kLzZ57ztotWzgZsxXlVYb8U9LG0UsQ22luRd04hIU4mplhHh6vKuVtRq34I7ZXJVDj0d9A22xuzpc4Poe7oBDtiBUL3eO+SPkjlN/EGeTyHk4eAxAVvDe59RJ2g89h5oyZFgTaWpAQ== admin@space.docker"

# registry
REGISTRY_LOCAL_HOST: reg.local
REGISTRY_LOCAL: "{{ REGISTRY_LOCAL_HOST }}:5000/k8s/"
REGISTRY_REMOTE: "registry.cn-qingdao.aliyuncs.com/wod/"
# REGISTRY_REMOTE_HOST: "172.16.11.23:5000"
REGISTRY_REMOTE_SPLIT: ":"
REGISTRY_DATA_PATH: /etc/kubernetes/data/registry

K8S_IMAGES: 
  KUBELET:
    NAME: hyperkube
    VERSION: "v1.14.1"
  KUBE-PROXY:
    NAME: kube-proxy
    VERSION: "v1.14.1"
  PAUSE: 
    NAME: pause-amd64
    VERSION: "3.1"
  REGISTRY:
    NAME: registry
    VERSION: "2.7.1"
  ETCD:
    NAME: etcd
    VERSION: "v3.3.10"
  FLANNEL:
    NAME: flannel
    VERSION: "v0.11.0"
  KUBE-ROUTER:
    NAME: kube-router
    VERSION: "v0.2.5"
  BUSYBOX:
    NAME: busybox
    VERSION: "1.30"
  NGINX:
    NAME: nginx
    VERSION: "1.15.3-alpine"
  COREDNS:
    NAME: coredns
    VERSION: "1.5.0"
  DASHBOARD:
    NAME: kubernetes-dashboard-amd64
    VERSION: "v1.10.1"
  HEAPSTER:
    NAME: heapster-amd64
    VERSION: "v1.5.4"
  ADDON-RESIZER:
    NAME: addon-resizer
    VERSION: "1.8.3"
  KUBECTL:
    NAME: kubectl
    VERSION: "v1.14.1"
  ETCDCTL:
    NAME: etcdctl
    VERSION: "v3.3.10"
  KEEPALIVED:
    NAME: keepalived
    VERSION: "1.4.5"
  HELM:
    NAME: helm
    VERSION: "v2.13.1"
  TILLER:
    NAME: tiller
    VERSION: "v2.13.1"
  TRAEFIK:
    NAME: traefik
    VERSION: "v1.7.10-alpine"    

# rkt images
RKT_ACI_REGISTRY: "registry-{{ K8S_IMAGES['REGISTRY']['VERSION'] }}.aci"
RKT_ACI_ETCD: "etcd-{{ K8S_IMAGES['ETCD']['VERSION'] }}.aci"
RKT_ACI_KUBELET: "{{ K8S_IMAGES['KUBELET']['NAME'] }}-{{ K8S_IMAGES['KUBELET']['VERSION'] }}.aci"

# ctl tools
RKT_ACI_REGISTRY_DATA: "registry-data-{{ K8S_IMAGES['KUBELET']['VERSION'] }}"

# k8s adv option.
K8S_NETWORK_PLUGIN: kube-router
K8S_CNI_BIN: cni-plugins-amd64-v0.7.5
K8S_POD_NETWORK: 10.2.0.0/16
K8S_SERVICE_IP_RANGE: 10.3.0.0/16
K8S_SERVICE_PORT_RANGE: 10000-32767
K8S_SERVICE_IP: 10.3.0.1
K8S_DNS_SERVICE_IP: 10.3.0.10
K8S_ADVERTISE_IP: "{{ ansible_default_ipv4['address'] }}"
K8S_PORT: 6443
K8S_ADMIN_PWD: abcd2018
K8S_MASTER_DOMAIN: k8s.wodcloud.local
K8S_MASTER_PORT: "{{ K8S_PORT }}"

# ubuntu
DEB_LIBLTDL7: libltdl7_2.4.6-0.1_amd64.deb
DEB_IPTABLE: iptables_1.6.0-2ubuntu3_amd64.deb
DEB_DOCKER: docker-engine_1.13.1-0~ubuntu-xenial_amd64.deb
DEB_RKT: rkt_1.30.0-1_amd64.deb

# centos
YUM_RKT: rkt-1.30.0-1.x86_64.rpm

# other
HTTP_SERVER: https://dl.wodcloud.com/k8s

CLOUD_IMAGES: 
  # STORAGEOS-NODE:
  #   NAME: storageos-node
  #   VERSION: "1.0.0-rc4"
  # STORAGEOS-INIT:
  #   NAME: storageos-init
  #   VERSION: "0.1"
  # K8SCSI-DRIVER-REGISTRAR:
  #   NAME: k8scsi-driver-registrar
  #   VERSION: "v0.2.0"
  # K8SCSI-CSI-PROVISIONER:
  #   NAME: k8scsi-csi-provisioner
  #   VERSION: "v0.3.0"
  # K8SCSI-CSI-ATTACHER:
  #   NAME: k8scsi-csi-attacher
  #   VERSION: "v0.3.0"
  # SAMEERSBN-GITLAB:
  #   NAME: sameersbn-gitlab
  #   VERSION: "11.2.3"
  # SAMEERSBN-POSTGRESQL:
  #   NAME: sameersbn-postgresql
  #   VERSION: "10"
  # SAMEERSBN-REDIS:
  #   NAME: sameersbn-redis
  #   VERSION: "4.0.9-1"
  # HARBOR-UI:
  #   NAME: harbor-ui
  #   VERSION: "v1.6.0"
  # HARBOR-ADMINSERVER:
  #   NAME: harbor-adminserver
  #   VERSION: "v1.6.0"
  # HARBOR-JOBSERVICE:
  #   NAME: harbor-jobservice
  #   VERSION: "v1.6.0"
  # HARBOR-DB:
  #   NAME: harbor-db
  #   VERSION: "v1.6.0"
  # HARBOR-REGISTRY:
  #   NAME: registry
  #   VERSION: "2.7.1" 
  # HARBOR-CHARTMUSEUM:
  #   NAME: chartmuseum-photon
  #   VERSION: "dev"
  # HARBOR-CLAIR:
  #   NAME: clair-photon
  #   VERSION: "dev"
  # HARBOR-REDIS:
  #   NAME: redis
  #   VERSION: "4.0.1-alpine"
  # HARBOR-NOTARY-SERVER:
  #   NAME: notary-server-photon
  #   VERSION: "dev"
  # HARBOR-SIGNER-SERVER:
  #   NAME: notary-signer-photon
  #   VERSION: "dev"
  # CHARTMUSEUM:
  #   NAME: chartmuseum
  #   VERSION: "v0.7.1"
  # CLAIR:
  #   NAME: clair
  #   VERSION: "v2.0.6"
  # NOTARY-SERVER:
  #   NAME: notary-server
  #   VERSION: "0.5.0"
  # DRONE-SERVER:
  #   NAME: drone-server
  #   VERSION: "0.8.4-4"
  # DRONE-AGENT:
  #   NAME: drone-agent
  #   VERSION: "0.8.4-4"
  # STORAGEOS-CHART:
  #   NAME: "storageos-chart"
  #   VERSION: "1.0.0-rc4"
  # GITLAB-CHART:
  #   NAME: "gitlab-chart"
  #   VERSION: "11.2.3"
  # DRONE-CHART:
  #   NAME: "drone-chart"
  #   VERSION: "0.8.4-4"
  # HARBOR-CHART:
  #   NAME: "harbor-chart"
  #   VERSION: "v1.6.0"
  # GITLAB:
  #   NAME: "sameersbn-gitlab"
  #   VERSION: "11.2.3"
  # GITLAB-POSTGRESQL:
  #   NAME: "sameersbn-postgresql"
  #   VERSION: "10"
  # GITLAB-REDIS:
  #   NAME: "sameersbn-redis"
  #   VERSION: "4.0.9-1"
  # CLOUD-CHART:
  #   NAME: "cloud-chart"
  #   VERSION: "v1.0"
  # CLOUD-REDIS:
  #   NAME: "redis"
  #   VERSION: "4.0.10"
  # CLOUD-MYSQL:
  #   NAME: "mysql"
  #   VERSION: "5.6.36"
  # CLOUD-INITMYSQL:
  #   NAME: "mysql-init"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-DEX:
  #   NAME: "awecloud-dex"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-API:
  #   NAME: "awecloud-api"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-DEPLOY:
  #   NAME: "awecloud-deploy"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-HARBOR:
  #   NAME: "awecloud-harbor"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-KUBERNETES:
  #   NAME: "awecloud-kubernetes"
  #   VERSION: "1.8.4"
  # CLOUD-AWECLOUD-REST:
  #   NAME: "awecloud-rest"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-LOGIN:
  #   NAME: "awecloud-login"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-UI:
  #   NAME: "awecloud-ui"
  #   VERSION: "1.0.0"
  # CLOUD-AWECLOUD-USERS:
  #   NAME: "awecloud-users"
  #   VERSION: "1.0.0"

K8S_DOMAIN: "wodcloud.local"

K8S_DASHBOARD:
  HOST: "k8s.{{ K8S_DOMAIN }}"