---
# iface
IFACE: "{{ ansible_default_ipv4['interface'] }}"

# host define
HOST_IP: "{{ 'ansible_'+IFACE['ipv4']['address'] }}"

# /root/.ssh
SSH_KEYS: 
  ansible: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCJNFRbNc0SsHa/+mWB71z7SLPH9rQpwEqGbRo7q466a97h3bejNav9wc9AKmepHPfRw7DJfSmWO3lGBya0QkXMYXVvtfcWPvZZDlar5JK/ZsC8HGOpwVLdd1uUfyPu2qM0sjRNA/Ty8PDMkS5dSyZAJNlxUAILRpepkYoT8jhrw== ansible@space.docker"
  admin: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCrQGlgFB4TGjJCNk3mJEjgId2Td054T642kLzZ57ztotWzgZsxXlVYb8U9LG0UsQ22luRd04hIU4mplhHh6vKuVtRq34I7ZXJVDj0d9A22xuzpc4Poe7oBDtiBUL3eO+SPkjlN/EGeTyHk4eAxAVvDe59RJ2g89h5oyZFgTaWpAQ== admin@space.docker"

# docker
DOCKER_DATA_PATH: /var/lib/docker

# registry
REGISTRY_LOCAL_HOST: reg.local
REGISTRY_LOCAL: "{{ REGISTRY_LOCAL_HOST }}:5000/k8s/"

# REGISTRY_REMOTE_HOST: "172.16.11.23:5000"
REGISTRY_REMOTE: "registry.cn-qingdao.aliyuncs.com/wod/"
REGISTRY_DATA_PATH: /etc/kubernetes/data/registry

K8S_IMAGES: 
  KUBELET:
    NAME: hyperkube
    VERSION: "v1.14.1"
  KUBE-APISERVER:
    NAME: kube-apiserver
    VERSION: "v1.14.1"
  KUBE-CONTROLLER-MANAGER:
    NAME: kube-controller-manager
    VERSION: "v1.14.1"
  KUBE-SCHEDULER:
    NAME: kube-scheduler
    VERSION: "v1.14.1"            
  KUBE-PROXY:
    NAME: kube-proxy
    VERSION: "v1.14.1"
  KUBECTL:
    NAME: kubectl
    VERSION: "v1.14.1"    
  PAUSE: 
    NAME: pause-amd64
    VERSION: "3.1"
  REGISTRY:
    NAME: registry
    VERSION: "2.7.1"
  ETCD:
    NAME: etcd
    VERSION: "v3.3.10"
  FLANNEL:
    NAME: flannel
    VERSION: "v0.11.0"
  KUBE-ROUTER:
    NAME: kube-router
    VERSION: "v0.2.5"
  BUSYBOX:
    NAME: busybox
    VERSION: "1.30"
  NGINX:
    NAME: nginx
    VERSION: "1.15.3-alpine"
  COREDNS:
    NAME: coredns
    VERSION: "1.5.0"
  DASHBOARD:
    NAME: kubernetes-dashboard-amd64
    VERSION: "v1.10.1"
  HEAPSTER:
    NAME: heapster-amd64
    VERSION: "v1.5.4"
  ADDON-RESIZER:
    NAME: addon-resizer
    VERSION: "1.8.3"
  ETCDCTL:
    NAME: etcdctl
    VERSION: "v3.3.10"
  KEEPALIVED:
    NAME: keepalived
    VERSION: "1.4.5"
  HELM:
    NAME: helm
    VERSION: "v2.13.1"
  TILLER:
    NAME: tiller
    VERSION: "v2.13.1"
  TRAEFIK:
    NAME: traefik
    VERSION: "v1.7.10-alpine"    

# rkt images
RKT_ACI_REGISTRY: "registry-{{ K8S_IMAGES['REGISTRY']['VERSION'] }}.aci"
RKT_ACI_ETCD: "etcd-{{ K8S_IMAGES['ETCD']['VERSION'] }}.aci"
RKT_ACI_KUBELET: "{{ K8S_IMAGES['KUBELET']['NAME'] }}-{{ K8S_IMAGES['KUBELET']['VERSION'] }}.aci"

# ctl tools
RKT_ACI_REGISTRY_DATA: "registry-data-{{ K8S_IMAGES['KUBELET']['VERSION'] }}"

# k8s adv option.
K8S_NETWORK_PLUGIN: kube-router
K8S_CNI_BIN: cni-plugins-amd64-v0.7.5
K8S_POD_NETWORK: 10.2.0.0/16
K8S_SERVICE_IP_RANGE: 10.3.0.0/16
K8S_SERVICE_PORT_RANGE: 10000-32767
K8S_SERVICE_IP: 10.3.0.1
K8S_DNS_SERVICE_IP: 10.3.0.10
K8S_ADVERTISE_IP: "{{ 'ansible_'+IFACE['ipv4']['address'] }}"
K8S_PORT: 6443
K8S_ADMIN_PWD: abcd2018
K8S_MASTER_DOMAIN: k8s.wodcloud.local
K8S_MASTER_PORT: "{{ K8S_PORT }}"

# ubuntu
DEB_LIBLTDL7: libltdl7_2.4.6-0.1_amd64.deb
DEB_IPTABLE: iptables_1.6.0-2ubuntu3_amd64.deb
DEB_DOCKER: docker-engine_1.13.1-0~ubuntu-xenial_amd64.deb
DEB_RKT: rkt_1.30.0-1_amd64.deb

# centos
YUM_RKT: rkt-1.30.0-1.x86_64.rpm

# other
HTTP_SERVER: https://dl.wodcloud.com/k8s

CLOUD_IMAGES: 

K8S_DOMAIN: "wodcloud.local"

K8S_DOMAIN_ADDONS:
  DASHBOARD: "k8s.{{ K8S_DOMAIN }}"
  TRAEFIK: "traefik.{{ K8S_DOMAIN }}"
  HUB: "hub.{{ K8S_DOMAIN }}"