---
# system options
SSH_INSTALL_KEYS: 
  - ansible
  - admin

# etcd options
ETCD_CLUSTER_ROLE: 
  systech14: etcd

# k8s option
K8S_CLUSTER_ROLE: 
  systech14: master

# registry options
REGISTRY_LOCAL_HOSTNAME: systech14
REGISTRY_LOCAL_IP: "{{ hostvars['systech14']['ansible_default_ipv4']['address'] }}"  

# one master
K8S_MASTER_IP: "{{ hostvars['systech14']['ansible_default_ipv4']['address'] }}"
K8S_MASTER_PORT: "{{ K8S_PORT }}"

# # three master ha-cluster
# # vip
# K8S_MASTER_IP: "127.0.0.1"
# # vip interface
# K8S_MASTER_INTERFACE: "eth0"
# K8S_MASTER_PORT: "8443"