---
# system options
SSH_INSTALL_KEYS: 
  - ansible
  - admin

# registry options
REGISTRY_LOCAL_HOSTNAME: systech14
REGISTRY_LOCAL_IP: "{{ hostvars['systech14']['ansible_default_ipv4']['address'] }}"

# etcd options
ETCD_CLUSTER_ROLE: 
  systech14: etcd

# k8s option
K8S_CLUSTER_ROLE: 
  systech14: master

K8S_MASTER_IP: "{{ hostvars['systech14']['ansible_default_ipv4']['address'] }}"