- hosts: all
  roles:
  - role: wod.registry-cache-cloud
    when: "inventory_hostname == REGISTRY_LOCAL_HOSTNAME"
  - role: wod.k8s-helm
    when: "inventory_hostname == REGISTRY_LOCAL_HOSTNAME"
  - role: wod.k8s-storageos
    when: "inventory_hostname == REGISTRY_LOCAL_HOSTNAME"