- hosts: all
  gather_facts: False
  roles:
  - wod.python

- hosts: all
  # vars:
  #   REGISTRY_LOCAL: "registry.cn-qingdao.aliyuncs.com/wod/"
  roles:
  - role: wod.timezone
  - role: wod.docker
  - role: wod.rkt
  - role: wod.sys
  - role: wod.k8s-ssl    
  - role: wod.etcd
    when: "ETCD_CLUSTER_ROLE[inventory_hostname] is defined"
  - role: wod.k8s-master
    when: "K8S_CLUSTER_ROLE[inventory_hostname] is defined and K8S_CLUSTER_ROLE[inventory_hostname] == 'master'"
  - role: wod.k8s-kubectl
    when: "K8S_CLUSTER_ROLE[inventory_hostname] is defined and K8S_CLUSTER_ROLE[inventory_hostname] == 'master'"
  - role: wod.k8s-worker
  - role: wod.k8s-label
    when: "inventory_hostname == REGISTRY_LOCAL_HOSTNAME"
  - role: wod.k8s-cni
  - role: wod.flannel
    when: "K8S_NETWORK_PLUGIN == 'flannel'"
  - role: wod.kube-router
    when: "K8S_NETWORK_PLUGIN == 'kube-router'"
  - role: wod.calico
    when: "K8S_NETWORK_PLUGIN == 'calico'"        
  - role: wod.cilium
    when: "K8S_NETWORK_PLUGIN == 'cilium'"
  - role: wod.k8s-addon
    when: "inventory_hostname == REGISTRY_LOCAL_HOSTNAME"
  - role: wod.k8s-helm
    when: "inventory_hostname == REGISTRY_LOCAL_HOSTNAME"