- name: mkdir -p /etc/rkt/paths.d
  raw: mkdir -p /etc/rkt/paths.d

- name: check need /etc/rkt/paths.d/paths.json
  raw: stat /etc/rkt/paths.d/paths.json
  register: need_rkt_paths
  ignore_errors: True

- name: template /etc/rkt/paths.d/paths.json
  template: src=paths.json dest=/etc/rkt/paths.d/paths.json mode=0644
  when: need_rkt_paths is failed

- name: check images exists
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    RKT_DATA_PATH: '{{ RKT_DATA_PATH }}'
  script: checkimages.sh

- name: install rkt
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    YUM_RKT: '{{ YUM_RKT }}'
  script: "{{ lookup('first_found', findme)}}"
  vars:
    findme:
      - install-{{ ansible_distribution }}.sh  
      - install.sh