- name: check need helm
  raw: stat /opt/bin/helm
  register: need_cli_helm
  ignore_errors: True

- name: template helm.sh
  template: src=helm.sh dest=/etc/kubernetes/scripts/helm.sh mode=0755
  when:
  - need_cli_helm | failed

- name: /etc/kubernetes/scripts/helm.sh
  raw: /etc/kubernetes/scripts/helm.sh
  when:
  - need_cli_helm | failed