- name: template helm.sh
  template: src=helm.sh dest=/etc/kubernetes/scripts/helm.sh mode=0755

- name: /etc/kubernetes/scripts/helm.sh
  raw: /etc/kubernetes/scripts/helm.sh

- name: template rbac-tiller.yml
  copy: src=rbac-tiller.yml dest=/etc/kubernetes/addons/kube-system/rbac-tiller.yml