- name: check need manifests/kube-keepalived.yaml
  raw: stat /etc/kubernetes/manifests/kube-keepalived.yaml
  register: need_manifests_keepalived
  ignore_errors: True

- name: template manifests/kube-keepalived.yaml
  template: src=kube-keepalived.yaml dest=/etc/kubernetes/manifests/kube-keepalived.yaml
  when: need_manifests_keepalived is failed