- name: check need ssl/token.csv
  raw: stat /etc/kubernetes/ssl/token.csv
  register: need_ssl_token
  ignore_errors: True

- name: template ssl/token.csv
  template: src=ssl/token.csv dest=/etc/kubernetes/ssl/token.csv
  when: need_ssl_token is failed  

- name: template manifests/kube-apiserver.yaml
  template: src=manifests/kube-apiserver.yaml dest=/etc/kubernetes/manifests/kube-apiserver.yaml

- name: template manifests/kube-controller-manager.yaml
  template: src=manifests/kube-controller-manager.yaml dest=/etc/kubernetes/manifests/kube-controller-manager.yaml

- name: template manifests/kube-scheduler.yaml
  template: src=manifests/kube-scheduler.yaml dest=/etc/kubernetes/manifests/kube-scheduler.yaml
