- name: Run prepare.sh
  environment:
    HTTP_SERVER: '{{ HTTP_SERVER }}'
    RKT_ACI_KUBELET: '{{ RKT_ACI_KUBELET }}'
    REGISTRY_LOCAL: '{{ REGISTRY_LOCAL }}'
    REGISTRY_KUBELET_REPO: '{{ K8S_IMAGES["KUBELET"]["NAME"] }}'
    REGISTRY_KUBELET_VERSION: '{{ K8S_IMAGES["KUBELET"]["VERSION"] }}' 
  script: scripts/prepare.sh

- name: mkdir -p /etc/kubernetes/config
  raw: mkdir -p /etc/kubernetes/config

- name: copy config/kubelet.yaml
  copy: src=config/kubelet.yaml dest=/etc/kubernetes/config/kubelet.yaml

- name: copy scripts/kubelet.sh
  template: src=scripts/kubelet.sh dest=/etc/kubernetes/scripts/kubelet.sh mode=0755

- name: check need ssl/admin.csv
  raw: stat /etc/kubernetes/ssl/admin.csv
  register: need_ssl_admin
  ignore_errors: True

- name: template ssl/admin.csv
  template: src=ssl/admin.csv dest=/etc/kubernetes/ssl/admin.csv
  when: need_ssl_admin is failed

- name: check need ssl/token.csv
  raw: stat /etc/kubernetes/ssl/token.csv
  register: need_ssl_token
  ignore_errors: True

- name: template ssl/token.csv
  template: src=ssl/token.csv dest=/etc/kubernetes/ssl/token.csv
  when: need_ssl_token is failed  

- name: template manifests/kube-apiserver.yaml
  template: src=manifests/kube-apiserver.yaml dest=/etc/kubernetes/manifests/kube-apiserver.yaml

- name: template manifests/kube-controller-manager.yaml
  template: src=manifests/kube-controller-manager.yaml dest=/etc/kubernetes/manifests/kube-controller-manager.yaml

- name: template manifests/kube-scheduler.yaml
  template: src=manifests/kube-scheduler.yaml dest=/etc/kubernetes/manifests/kube-scheduler.yaml

- name: check need services/k8s-kubelet.service
  raw: stat /etc/systemd/system/k8s-kubelet.service
  register: need_services_kubelet
  ignore_errors: True

- name: template services/k8s-kubelet.service
  template: src=services/kubelet.service dest=/etc/systemd/system/k8s-kubelet.service

- name: start services k8s-kubelet.service
  raw: systemctl daemon-reload && systemctl enable k8s-kubelet.service && systemctl start k8s-kubelet.service
  when: need_services_kubelet is failed